services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: taskflow-postgres.ctckymawww1t.eu-north-1.rds.amazonaws.com
      DB_PORT: "5432"
      DB_NAME: taskflow
    expose:
      - "5000"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
