name: TaskFlow CI

on:
  pull_request:
    branches:
      - main
      

  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create CI environment file
        run: cp backend/.env.example backend/.env

      - name: Build Docker images
        run: docker compose --env-file backend/.env build
      
      - name: Start application
        run: docker compose --env-file backend/.env up -d

      - name: Check containers status
        run:  docker compose --env-file backend/.env ps

      - name: Test backend API
        run:  curl --fail http://localhost:5000/ 
      
      - name: Test task API
        run: curl --fail http://localhost:5000/tasks
        
      
      
          

